kind: Module
type: helm
name: docker-daemon
description: Docker daemon used for in-cluster building
releaseName: garden-docker-daemon
dependencies:
  - build-sync
values:
  mode: ${var.builder-mode}
  resources:
    limits:
      cpu: ${var.builder-limits-cpu}
      memory: ${var.builder-limits-memory}
    requests:
      cpu: ${var.builder-requests-cpu}
      memory: ${var.builder-requests-memory}
  registry:
    hostname: ${var.registry-hostname || "foo"}
    # tlsSecretName: ${variables.registry-tls-secret-name}
  storage:
    size: ${var.builder-storage-size}
    storageClass: ${var.builder-storage-class}
  buildSync:
    volume:
      name: ${var.sync-volume-name}
