kind: Module
name: nfs-provisioner
description: Provisioner for NFS volumes used by Garden system services
type: helm
releaseName: garden-nfs-provisioner-v2
values:
  nameOverride: garden-nfs-provisioner-v2
  fullnameOverride: garden-nfs-provisioner-v2
  persistence:
    enabled: true
    size: ${var.nfs-storage-size}
    storageClass: ${var.nfs-storage-class}
  storageClass:
    name: ${var.sync-storage-class}
