apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-daemon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
    helm.sh/chart: {{ include "docker-daemon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    # We only want one instance at a time, because we're using the same volume for the data
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: garden-docker-data
          persistentVolumeClaim:
            claimName: garden-docker-data
        - name: garden-build-sync
          persistentVolumeClaim:
            claimName: {{ .Values.buildSync.volume.name }}
        # - name: garden-registry-tls
        #   secret:
        #     secretName: foo
        #     items:
        #       - key: tls.crt
        #         path: localhost:5000/ca.crt
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: docker
              containerPort: 2375
              protocol: TCP
          securityContext:
            privileged: true
          livenessProbe:
            tcpSocket:
              port: 2375
          readinessProbe:
            tcpSocket:
              port: 2375
          volumeMounts:
            - name: garden-docker-data
              mountPath: /var/lib/docker
            - name: garden-build-sync
              mountPath: /garden-build
              # Need to mount the registry cert so that the daemon trusts it
            # - name: garden-registry-tls
            #   mountPath: /etc/docker/certs.d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: proxy
          image: "basi/socat:v0.1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              socat TCP-LISTEN:5000,fork TCP:{{ .Values.registry.hostname }}:5000
          ports:
            - name: proxy
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5000
          readinessProbe:
            tcpSocket:
              port: 5000
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
