apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "garden-build-sync.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
    helm.sh/chart: {{ include "garden-build-sync.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "garden-build-sync.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: garden-build-sync
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
      containers:
        - name: sync
          image: "gardendev/rsync:0.1"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: rsync
              containerPort: 873
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 873
          readinessProbe:
            tcpSocket:
              port: 873
          volumeMounts:
            - mountPath: /data
              name: garden-build-sync
          env:
            # The service is not exposed at all outside the cluster, so this should be all good.
            - name: ALLOW
              value: "0.0.0.0/0"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
