apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.request }}
{{- if .Values.storage.storageClass }}
{{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
{{- end }}
{{- end }}